import { createSlice } from '@reduxjs/toolkit';

export const SORTS={
  DEFAULT: "Added (Newest)",
  ALPHA_ASC: "Alphabetical (Asc)",
  ALPHA_DSC: "Alphabetical (Dsc)",
  ADDED: "Added (Oldest)"
}

export const CATEGORIES = {
  LEFTOVERS: "Leftovers",
  MEAT: "Meat",
  SAUCES: "Sauces",
  VEG: "Veg"
}

export const ALL_CATEGORIES = {
  ALL: "All",
  ...CATEGORIES
}

const initialState = {
  filter: "",
  sort: SORTS.DEFAULT,
  category: ALL_CATEGORIES.ALL,
};


export const filtersSlicer = createSlice({
  name: 'filters',
  initialState,
  // The `reducers` field lets us define reducers and generate associated actions
  reducers: {
    setFilter: (state, action) => {
      state.filter = action.payload;
    },
    setSort: (state, action) => {
      if(Object.values(SORTS).includes(action.payload)) {
        state.sort = action.payload;
      }
    },
    setCategory: (state, action) => {
      if(Object.values(ALL_CATEGORIES).includes(action.payload)) {
        state.category = action.payload;
      }
    },
  },
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
  extraReducers: (builder) => {},
});

export const {
  setFilter,
  setSort,
  setCategory,
} = filtersSlicer.actions;

export default filtersSlicer.reducer;
